=== dcwebmaven/EmployeeListwithSchemaXML/Employees.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Employees">
     <xs:complexType>
     <xs:sequence>
              <xs:element name="Employee" minOccurs="0" maxOccurs="unbounded"/>
                   <xs:complexType>
                   <xs:sequence>
                      <xs:element name="First" type="xs:string"/>
                      <xs:element name="Last" type="xs:string"/>
                      <xs:element name="Phone" type="xs:string"/>
                   </xs:sequence>
                   </xs:complexType>
     </xs:sequence>
     </xs:complexType>  
         </xs:element>
</xs:schema>

=== dcwebmaven/EmployeeListwithSchemaXML/xmlLesson4obj1.xml
<?xml version="1.0"?>
<!DOCTYPE Employees>
<Employees xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="Employees.xsd">
 <Employee>
 <First>John</First>
 <Last>Smith</Last>
  <Phone>1-800-123-4567</Phone>
 </Employee>
  <Employee>
 <First>Alexandra</First>
 <Last>Borodin</Last>
  <Phone>1-800-123-4567</Phone>
 </Employee>
</Employees>
